import Head from "next/head";
import { Inter } from "@next/font/google";
import Nav from "@/components/Nav";
import { SVGProps } from "react";
import Features from "@/components/Features";
import Recruitment from "@/components/Recruitment";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Gable Executive Search</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Nav
          text={""}
          Icon={function (props: SVGProps<SVGSVGElement>): JSX.Element {
            throw new Error("Function not implemented.");
          }}
        />
        <Features />
        <Recruitment />
      </main>
    </>
  );
}
