import Head from "next/head";
import { Inter } from "@next/font/google";
import { SVGProps } from "react";
import Features from "@/components/Features";
import Recruitment from "@/components/Recruitment";
import Reviews from "@/components/Reviews";
import Contact from "@/components/Contact";
import Footer from "@/components/Footer";
import Landing from "@/components/Landing";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>GableExecutiveSearch</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />
        <Landing
          text={""}
          Icon={function (props: SVGProps<SVGSVGElement>): JSX.Element {
            throw new Error("Function not implemented.");
          }}
        />
        <Features />
        <Recruitment />
        <Reviews />
        <Contact />
        <Footer />
      </main>
    </>
  );
}
